### ISSUE TITLE
nesting {{#repeat {{int min max}}}}

### ISSUE THREAD

**Issue by everdrone** [webroo/dummy-json#27] opened 2017-09-10 09:07 UTC
please allow nesting `{{int min max}}` inside `{{lorem N}}`, `{{#repeat N}}`

**Comment by filipeovercom** [comment] 2020-03-26 15:23
Duplicate of #18

**Comment by webroo** [comment] 2020-07-11 12:41
As of v3.0.0 you can repeat a block a random number of times by giving min and max bounds:
`{{repeat min=5 max=10}}`

and you can use the same syntax with the lorem ipsum helper:
`{{lorem min=20 max=40}}`

**Closed by webroo** 2020-07-11 12:41 UTC
